import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const prod = process.argv[2] === "production";
const projectRoot = path.dirname(fileURLToPath(import.meta.url));
const safeImmediatePath = path.join(projectRoot, "src/shims/safeImmediate.js");
const safeSetImmediatePath = path.join(projectRoot, "src/shims/safeSetImmediate.js");
const jszipSourcePath = path.join(projectRoot, "node_modules/jszip/lib/index.js");

const reviewSafeSchedulerShims = {
  name: "review-safe-scheduler-shims",
  setup(build) {
    build.onResolve({ filter: /^immediate$/ }, () => ({ path: safeImmediatePath }));
    build.onResolve({ filter: /^setimmediate$/ }, () => ({ path: safeSetImmediatePath }));
    build.onResolve({ filter: /^jszip$/ }, () => ({ path: jszipSourcePath }));
  }
};

const context = await esbuild.context({
  banner: { js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */" },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands", "@codemirror/language", "@codemirror/lint", "@codemirror/search", "@codemirror/state", "@codemirror/view", "@lezer/common", "@lezer/highlight", "@lezer/lr", ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [reviewSafeSchedulerShims]
});

if (prod) {
  await context.rebuild();
  await context.dispose();

  const buildDir = path.join(projectRoot, "build");
  fs.mkdirSync(buildDir, { recursive: true });
  for (const file of ["main.js", "styles.css", "manifest.json"]) {
    fs.copyFileSync(path.join(projectRoot, file), path.join(buildDir, file));
  }
} else {
  await context.watch();
}
